### ISSUE TITLE
[Bug] Repairing materal becomes unstackable

### ISSUE THREAD

**Issue by Rad586** [TrueHorse/Enchantment-Preservation#6]
1.18.2 fabric.
**Environment:** 
fabric api and this mod.
**Desc:** 
Repairing material becomes unstackable after put into the anvil.
The unstackable item was added a tag that has no value(tag{}), it goes back to normal after thrown on the ground and picked up. 
**Steps to reproduce:**
1. /give @p minecraft:diamond_boots{Damage:50}
2. /give @p minecraft:diamond 64
3. Put down an anvil, open its gui, put the boots in the first slot, and a diamond the second slot. 
4. Don't repair, just grab the diamond back, and you'll find it becomes unstackable.

**Comment by TrueHorse** [comment]
Thank you for the detailed report, which made the problem easy to find and fix.
